[project]
name = "datamanager-python-tools"
version = "0.1.0"
description = "Python tools for Data Manager"
readme = "README.md"
requires-python = ">=3.13"
dynamic = ["dependencies"]

[tool.setuptools.dynamic.dependencies]
file = "requirements.txt"