name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    permissions:
      actions: read
      checks: read
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    - name: Install dependencies
      run: |
        uv pip install --system flake8 pytest
        if [ -f requirements.txt ]; then uv pip install --system -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - uses: astral-sh/ruff-action@v1
      with:
        args: |
          format
          --check
          --line-length 120
          --diff
        src: ./app
  build:
    uses: ./.github/workflows/docker.yml
    needs: [lint]
    permissions:
      checks: read
      contents: read
      packages: write
